### ISSUE TITLE
能否提供更详细的部署说明吗？

### ISSUE THREAD

**Issue by suoba** [miaowm5/RSSGen#3]
能否提供更详细的部署说明吗？也许有些在你看来太简单了，但是对我来说真的太不简单了，昨天一下午+晚上都没搞定。。。。
求详细步骤部署说明！
事实上，如果你写个像KeUploader那种安装部署的话那就最好不过了！几个命令就搞定了。
根据自己需求生成RSS，然后对接 KindleEar简直是完美的搭配啊！很好的idea，但是真的需要更加完好的的小白安装说明啊！

**Comment by miaowm5** [comment]
好的，这几天比较忙，周末加一个

**Comment by miaowm5** [comment]
https://github.com/miaowm5/RSSGen/blob/Release/guide/deploy/readme.md

**Comment by suoba** [comment]
按照教程搞定了。非常好。
剩下的就是定制自己的RSS了。
非常感谢！
